### ISSUE TITLE
GitHub Actions - Check for typos

### ISSUE THREAD

**Issue by over-engineer** [pressidium/pressidium-cookie-consent#137]
Enhance our GitHub Actions workflow by checking for typos in PRs. As @szepeviktor pointed out in #133, https://github.com/crate-ci/typos can be integrated into a workflow.

**Comment by szepeviktor** [comment]
here is a `.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "src/admin/components/Countries/countries.js",
    "src/admin/components/Countries/flags/",
    "src/admin/components/Countries/icons.js",
    "src/admin/components/Languages/flags/",
    "src/admin/components/Languages/icons.js",
    "src/admin/components/Languages/languages.js",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "=> 'yor'",
]

[default.extend-identifiers]
clen = "clen"
optin = "optin"

# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
```
